/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnitest_JNITest */

#ifndef _Included_jnitest_JNITest
#define _Included_jnitest_JNITest
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     jnitest_JNITest
     * Method:    printHelloWorld
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_jnitest_JNITest_printHelloWorld(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
