language: java
jdk:
    - openjdk13

install: true

script: "cd Aggregation; mvn test -B"

sudo: false

notifications:
  email:
    recipients:
      - junktogo@web.de
    on_success: change
    on_failure: always
