language: java

install: true

env:
  - MODULE=EnvironmentHandler
  - MODULE=ConfigurationDialog
  - MODULE=Launcher
  - MODULE=Membermanagement

script:
  - ant -buildfile $MODULE/build.xml -lib $MODULE/lib

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    recipients:
      - junktogo@web.de
    on_success: change
    on_failure: always
