language: java
install:
  - ant -buildfile EnvironmentHandler/build.xml -lib EnvironmentHandler/lib test
  - ant -buildfile ConfigurationDialog/build.xml -lib ConfigurationDialog/lib test
  - ant -buildfile Launcher/build.xml -lib Launcher/lib test
  - ant -buildfile Membermanagement/build.xml -lib Membermanagement/lib test

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
