language: java

install: true

script:
  - ant -buildfile EnvironmentHandler/build.xml -lib EnvironmentHandler/lib
  - ant -buildfile ConfigurationDialog/build.xml -lib ConfigurationDialog/lib
  - ant -buildfile Launcher/build.xml -lib Launcher/lib
  - ant -buildfile Membermanagement/build.xml -lib Membermanagement/lib

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
