language: java
install:
  - ant -buildfile EnvironmentHandler/build.xml
  - ant -buildfile ConfigurationDialog/build.xml
  - ant -buildfile Launcher/build.xml
  - ant -buildfile Membermanagement/build.xml

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
