language: java

install: true

jdk:
  - oraclejdk8

git:
    submodules: false

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    recipients:
      - junktogo@web.de
    on_success: change
    on_failure: always
