language: java

install: true

script: "cd Aggregation; mvn test -B"

jdk:
  - oraclejdk10

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    recipients:
      - junktogo@web.de
    on_success: change
    on_failure: always
