language: java
install:
  - ant EnvironmentHandler/build.xml
  - ant ConfigurationDialog/build.xml
  - ant Launcher/build.xml
  - ant Membermanagement/build.xml

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
